# Generated by Django 5.1 on 2024-09-01 16:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(db_index=True, max_length=40, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(db_index=True, max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image_path', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_primary', models.BooleanField(default=False)),
                ('file_size', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveefy.user', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='loveefy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(db_index=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_user_1', to='loveefy.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_user_2', to='loveefy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(db_index=True, max_length=25)),
                ('min_age', models.IntegerField(default=18, null=True)),
                ('max_age', models.IntegerField(default=65, null=True)),
                ('country', models.CharField(db_index=True, max_length=30, null=True)),
                ('region', models.CharField(max_length=30, null=True)),
                ('industry_major', models.CharField(db_index=True, default='any', max_length=50, null=True)),
                ('career', models.CharField(max_length=36)),
                ('education_level', models.CharField(default='any', max_length=40)),
                ('employment', models.CharField(max_length=20)),
                ('is_schooling', models.CharField(max_length=10)),
                ('fav_hobby', models.CharField(max_length=50)),
                ('wants_child', models.CharField(default='any', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveefy.user', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(db_index=True, max_length=150)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('sub_region', models.CharField(max_length=100)),
                ('longitude', models.IntegerField(null=True)),
                ('latitude', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveefy.user', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveefy.room')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='loveefy.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='loveefy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=36)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_user_1', to='loveefy.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_user_2', to='loveefy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_who_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='loveefy.user')),
                ('user_who_was_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='loveefy.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=20)),
                ('DOB', models.DateTimeField()),
                ('mobile_no', models.CharField(db_index=True, max_length=16, unique=True)),
                ('education_level', models.CharField(blank=True, max_length=36)),
                ('industry_major', models.CharField(max_length=25)),
                ('employment', models.CharField(blank=True, max_length=25)),
                ('is_schooling', models.CharField(blank=True, max_length=25)),
                ('career', models.CharField(blank=True, max_length=50, null=True)),
                ('has_child', models.CharField(default='no', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveefy.user', unique=True)),
            ],
        ),
    ]
